config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  resources :posts do
    resources :comments
  end
  get '/about', to: 'pages#about'
  
  root 'posts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  validates :body, :name, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments, dependent: :destroy
  validates :title, presence: true, length: {minimum: 5}
  validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(params[:comment].permit(:name, :body))

    redirect_to post_path(@post)
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy

    redirect_to post_path(@post)
  end  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :find_post, only: [:show, :edit, :update, :destroy]

  def index
    @posts = Post.all.order("created_at DESC")
  end

  def show
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    
    if  @post.save
      redirect_to @post
    else
      render "new"
    end    
  end
  
  def edit
  end
  
  def update
    if @post.update(post_params)
      redirect_to @post
    else
      render "edit" 
    end   
  end

  def destroy
    @post.destroy
    redirect_to root_path 
  end

  private
  def find_post
    @post = Post.find(params[:id])
  end   
  
  def post_params
    params.require(:post).permit(:title, :body)
  end  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<div class="comment clearfix">
  <div class="comment_content">
    <p class="comment_name"><strong><%= comment.name %></strong></p>
    <p class="comment_body"><%= comment.body %></p>
    <p class="comment_title"><%= time_ago_in_words(comment.created_at) %> Ago</p>
  </div>
  <% if user_signed_in? %>
    <p>
      <%= link_to 'Delete', [comment.post, comment], method: :delete, class: "button", data: {confirm: 'Are you sure?'} %>
    </p>
  <% end %>
</div>

app/views/comments/_form.html.erb
<%= form_with(model: [@post, @post.comments.build], remote: true) do |f| %>
  
  <p>
    <%= f.label :name%><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :body%><br>
    <%= f.text_field :body %>
  </p>
  <br>
  <% if user_signed_in? %>
    <p>
      <%= f.submit %>
    </p>
  <% else %>  
    <button class="button"><p class="sign_in"><%= link_to 'User Login', new_user_session_path %></p></button>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Foro</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', 'https://fonts.googleapis.com/css2?family=Raleway:wght@400;700&display=swap'%>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag 'favicon'%>
  </head>

  <body>
    <%= render "shared/sidebar"%>
    <%= render "shared/navigation"%>
    <%= render "shared/msg"%>
    <div id="main_content">
    <%= yield %>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<div id="page_wrapper">
  <div id="profile_image">
    <%= image_tag 'profile.jpg' %>
  </div>

  <div id="content">
    <h1>It's the famous Mr Cat</h1>
    <p>Enamel pin gluten-free mlkshk helvetica banh mi YOLO migas pork belly chillwave palo santo chia neutra bicycle rights four loko organic. Cornhole franzen tumblr biodiesel quinoa banjo microdosing tacos mumblecore skateboard. Hoodie mumblecore jianbing twee freegan fanny pack tbh distillery keffiyeh chillwave palo santo roof party. Pour-over chartreuse kitsch chia irony, af listicle activated charcoal fanny pack yr everyday carry photo booth fam stumptown. <br> <br>  Air plant humblebrag iceland ethical pitchfork. Cronut drinking vinegar tousled before they sold out ugh. Hexagon quinoa pour-over 3 wolf moon small batch everyday carry skateboard, hammock chia locavore DIY craft beer. Jean shorts mixtape knausgaard bicycle rights scenester skateboard stumptown, master cleanse tousled single-origin coffee waistcoat man braid cardigan. Green juice pabst cronut kombucha. Wayfarers kombucha dreamcatcher polaroid hella retro humblebrag before they sold out gluten-free freegan. Cliche thundercats meh swag gluten-free <br> <br> Portland lomo quinoa flexitarian biodiesel, fashion axe messenger bag tilde drinking vinegar health goth microdosing kogi banjo +1 subway tile. Migas tacos DIY pitchfork ramps yuccie paleo cliche ennui meh fixie marfa swag hashtag tumeric. Thundercats truffaut deep v, health goth mumblecore heirloom direct trade. Activated charcoal cold-pressed master cleanse, stumptown keytar cliche chillwave next level poke artisan meditation. Cred yuccie glossier locavore wayfarers, copper mug activated charcoal small batch fingerstache ennui prism actually tofu. Drinking vinegar succulents next level banh mi. Lumbersexual fixie schlitz green juice hammock, cred farm-to-table locavore snackwave wolf vinyl irony waistcoat.</p>
  </div>
</div>

app/views/posts/_form.html.erb
<%= form_with(model: @post, local:true) do |f| %>
  <% if @post.errors.any? %>
		<div id="errors">
			<h2><%= pluralize(@post.errors.count, "error") %> stopped this post from saving</h2>
			<ul>
				<% @post.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
  <p>
    <%= f.label :title %>
    <br>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :body %>
    <br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit :Submit %>
  </p> 
<% end%>

app/views/posts/edit.html.erb
<div id="page_wrapper"> 
  <h1>Edit your Post</h1>
  
  <%= render "form"%>
</div>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
  <div class="post_wrapper">
    <h2 class="title"><%= link_to post.title, post %></h2>
    <p class="date"><%= time_ago_in_words(post.created_at)%> ago</p>
    <p class="body"><%= truncate(post.body, length:100)%></p>
  </div>
<% end %>  

app/views/posts/new.html.erb
<div id="page_wrapper"> 
  <h1>Create a new Post</h1>
  
  <%= render "form"%>
  <%= link_to 'Back', root_path %>
</div> 

app/views/posts/show.html.erb
<div id="post_content">
  <h1 class="title">
    <%= @post.title %>
  </h1>
  <p class="body">
    <%= @post.body%>
  </p>
  <p class="date">
    Submitted <%= time_ago_in_words(@post.created_at) %> ago 
    <% if user_signed_in? %>
      | <%= link_to 'Edit', edit_post_path(@post) %> |
      <%= link_to 'Delete', post_path(@post), method: :delete, data: {confirm: "Are you sure?"} %>
    <% end %>
  </p>

  <div id="comments">
    <h2><%= @post.comments.count%> Comments </h2>
    <%= render @post.comments%>
    <h3> Join Discussion: </h3>
    <%= render "comments/form" %>
  </div>
  
</div>

<%= link_to 'Post feed', root_path, class: "button" %>

app/views/shared/_msg.html.erb
<% flash.each do |name, msg| %>
  <%= content_tag :div, msg, class:'alert' %>
<% end %>  

app/views/shared/_navigation.html.erb
<div id="main_content">
  <div id="header">
    <% if current_page?(root_path) %>
      <p>Post Feed</p>
    <% elsif current_page?(about_path) %>
      <p>My Site</p>
    <% else %>    
      <p><%= link_to 'Back to Post Feed', root_path %></p>
    <% end %>
    
    <% if user_signed_in? %>
      <div class="buttons">
        <button class="button"><%= link_to 'New Post', new_post_path %></button>
        <button class="button"><%= link_to 'Log Out', destroy_user_session_path, method: :delete %></button>
      </div>
    <% end %>  
  </div>
</div>

app/views/shared/_sidebar.html.erb
<div id="sidebar">
  <ul>
    <li class="category"><%= link_to 'Foro', root_path %></li>
    <li><%= link_to 'Posts', root_path %></li>
    <li><%= link_to 'About', about_path%></li>
  </ul>
  <% if !user_signed_in? %>
    <p class="sign_in"><%= link_to 'User Login', new_user_session_path %></p>
  <% end %>  
</div>